/**
 * Combined icon catalog for template icon pickers.
 * Includes legacy Font Awesome names plus Simple Icons brands.
 */

import {
  siDiscord,
  siBluesky,
  siMastodon,
  siInstagram,
  siFacebook,
  siX,
  siYoutube,
  siTiktok,
  siWhatsapp,
  siGithub,
  siGitlab,
  siReddit,
  siTelegram,
  siThreads,
  siSnapchat,
  siPinterest,
  siSpotify,
  siTwitch,
  siSteam,
  siMedium,
  siSubstack,
  siNotion,
  siFigma,
  siBehance,
  siDribbble,
  siDocker,
  siKubernetes,
  siVercel,
  siNetlify,
  siCloudflare,
  siNpm,
  siYarn,
  siPython,
  siJavascript,
  siTypescript,
  siReact,
  siNextdotjs,
  siWordpress,
  siShopify,
  siStripe,
} from 'simple-icons';

const LEGACY_FONT_AWESOME_ICONS = [
  { name: 'arrow-left', label: 'Pfeil Links' },
  { name: 'arrow-right', label: 'Pfeil Rechts' },
  { name: 'arrow-up', label: 'Pfeil Oben' },
  { name: 'arrow-down', label: 'Pfeil Unten' },
  { name: 'chevron-left', label: 'Chevron Links' },
  { name: 'chevron-right', label: 'Chevron Rechts' },
  { name: 'chevron-up', label: 'Chevron Oben' },
  { name: 'chevron-down', label: 'Chevron Unten' },
  { name: 'bars', label: 'Menü' },
  { name: 'angle-right', label: 'Winkel Rechts' },
  { name: 'plus', label: 'Plus / Hinzufügen' },
  { name: 'minus', label: 'Minus / Entfernen' },
  { name: 'trash', label: 'Trash / Löschen' },
  { name: 'trash-alt', label: 'Trash Alt' },
  { name: 'edit', label: 'Bearbeiten' },
  { name: 'pen', label: 'Stift' },
  { name: 'pencil', label: 'Bleistift' },
  { name: 'copy', label: 'Kopieren' },
  { name: 'paste', label: 'Einfügen' },
  { name: 'cut', label: 'Ausschneiden' },
  { name: 'undo', label: 'Rückgängig' },
  { name: 'redo', label: 'Wiederherstellen' },
  { name: 'search', label: 'Suchen' },
  { name: 'magnifying-glass', label: 'Lupe' },
  { name: 'eye', label: 'Auge / Anschauen' },
  { name: 'eye-slash', label: 'Auge durchgestrichen' },
  { name: 'binoculars', label: 'Fernglas' },
  { name: 'file', label: 'Datei' },
  { name: 'file-pdf', label: 'PDF-Datei' },
  { name: 'file-word', label: 'Word-Datei' },
  { name: 'file-excel', label: 'Excel-Datei' },
  { name: 'file-image', label: 'Bilddatei' },
  { name: 'folder', label: 'Ordner' },
  { name: 'folder-open', label: 'Ordner offen' },
  { name: 'folder-plus', label: 'Ordner Plus' },
  { name: 'download', label: 'Download' },
  { name: 'upload', label: 'Upload' },
  { name: 'cloud-download', label: 'Cloud Download' },
  { name: 'cloud-upload', label: 'Cloud Upload' },
  { name: 'check', label: 'Häkchen' },
  { name: 'check-circle', label: 'Häkchen Kreis' },
  { name: 'times', label: 'X / Schließen' },
  { name: 'times-circle', label: 'X Kreis' },
  { name: 'exclamation', label: 'Ausrufezeichen' },
  { name: 'exclamation-circle', label: 'Ausrufezeichen Kreis' },
  { name: 'exclamation-triangle', label: 'Warnung' },
  { name: 'question', label: 'Fragezeichen' },
  { name: 'question-circle', label: 'Fragezeichen Kreis' },
  { name: 'info-circle', label: 'Info' },
  { name: 'image', label: 'Bild' },
  { name: 'images', label: 'Bilder' },
  { name: 'video', label: 'Video' },
  { name: 'camera', label: 'Kamera' },
  { name: 'film', label: 'Film' },
  { name: 'music', label: 'Musik' },
  { name: 'volume-up', label: 'Lautstärke' },
  { name: 'volume-down', label: 'Lautstärke leiser' },
  { name: 'volume-mute', label: 'Stumm' },
  { name: 'envelope', label: 'Umschlag / Email' },
  { name: 'envelope-open', label: 'Umschlag offen' },
  { name: 'comment', label: 'Kommentar' },
  { name: 'comments', label: 'Kommentare' },
  { name: 'comments-o', label: 'Kommentare Outline' },
  { name: 'phone', label: 'Telefon' },
  { name: 'phone-square', label: 'Telefon Quadrat' },
  { name: 'share', label: 'Teilen' },
  { name: 'share-alt', label: 'Teilen Alt' },
  { name: 'link', label: 'Link' },
  { name: 'heart', label: 'Herz' },
  { name: 'heart-o', label: 'Herz Outline' },
  { name: 'star', label: 'Stern' },
  { name: 'star-o', label: 'Stern Outline' },
  { name: 'star-half', label: 'Stern halb' },
  { name: 'instagram', label: 'Instagram', prefix: 'fab' },
  { name: 'facebook-f', label: 'Facebook', prefix: 'fab' },
  { name: 'linkedin-in', label: 'LinkedIn', prefix: 'fab' },
  { name: 'x-twitter', label: 'X / Twitter', prefix: 'fab' },
  { name: 'youtube', label: 'YouTube', prefix: 'fab' },
  { name: 'tiktok', label: 'TikTok', prefix: 'fab' },
  { name: 'whatsapp', label: 'WhatsApp', prefix: 'fab' },
  { name: 'github', label: 'GitHub', prefix: 'fab' },
  { name: 'user', label: 'Benutzer' },
  { name: 'users', label: 'Benutzer mehrere' },
  { name: 'user-plus', label: 'Benutzer Plus' },
  { name: 'user-minus', label: 'Benutzer Minus' },
  { name: 'user-circle', label: 'Benutzer Kreis' },
  { name: 'user-circle-o', label: 'Benutzer Kreis Outline' },
  { name: 'briefcase', label: 'Koffer' },
  { name: 'money', label: 'Geld' },
  { name: 'dollar', label: 'Dollar' },
  { name: 'euro', label: 'Euro' },
  { name: 'pound', label: 'Pfund' },
  { name: 'credit-card', label: 'Kreditkarte' },
  { name: 'shopping-cart', label: 'Warenkorb' },
  { name: 'shopping-bag', label: 'Einkaufstasche' },
  { name: 'calendar', label: 'Kalender' },
  { name: 'clock-o', label: 'Uhr' },
  { name: 'th', label: 'Gitter' },
  { name: 'th-large', label: 'Gitter groß' },
  { name: 'th-list', label: 'Liste' },
  { name: 'list', label: 'Liste vertikal' },
  { name: 'list-ul', label: 'Ungeordnete Liste' },
  { name: 'list-ol', label: 'Geordnete Liste' },
  { name: 'columns', label: 'Spalten' },
  { name: 'cog', label: 'Zahnrad / Einstellungen' },
  { name: 'sliders', label: 'Schieberegler' },
  { name: 'toggle-on', label: 'Toggle An' },
  { name: 'toggle-off', label: 'Toggle Aus' },
  { name: 'wrench', label: 'Schraubenschlüssel' },
  { name: 'hammer', label: 'Hammer' },
  { name: 'screwdriver', label: 'Schraubendreher' },
  { name: 'database', label: 'Datenbank' },
  { name: 'server', label: 'Server' },
  { name: 'hdd-o', label: 'Festplatte' },
  { name: 'plug', label: 'Stecker' },
  { name: 'save', label: 'Speichern' },
  { name: 'floppy-o', label: 'Diskette' },
  { name: 'refresh', label: 'Aktualisieren' },
  { name: 'sync', label: 'Synchronisieren' },
  { name: 'spinner', label: 'Spinner' },
  { name: 'wheelchair', label: 'Rollstuhl' },
  { name: 'universal-access', label: 'Universeller Zugang' },
  { name: 'bell', label: 'Glocke' },
  { name: 'bell-o', label: 'Glocke Outline' },
  { name: 'home', label: 'Startseite' },
  { name: 'building', label: 'Gebäude' },
  { name: 'globe', label: 'Globus' },
  { name: 'lock', label: 'Schloss' },
  { name: 'unlock', label: 'Entsperrt' },
  { name: 'key', label: 'Schlüssel' },
  { name: 'flag', label: 'Flagge' },
  { name: 'bookmark', label: 'Lesezeichen' },
  { name: 'tag', label: 'Tag' },
  { name: 'tags', label: 'Tags' },
  { name: 'code', label: 'Code' },
  { name: 'bug', label: 'Bug' },
  { name: 'cube', label: 'Würfel' },
  { name: 'cubes', label: 'Würfel mehrere' },
].map((icon) => ({ ...icon, provider: 'font-awesome' }));

const SIMPLE_ICON_SET = [
  siDiscord,
  siBluesky,
  siMastodon,
  siInstagram,
  siFacebook,
  siX,
  siYoutube,
  siTiktok,
  siWhatsapp,
  siGithub,
  siGitlab,
  siReddit,
  siTelegram,
  siThreads,
  siSnapchat,
  siPinterest,
  siSpotify,
  siTwitch,
  siSteam,
  siMedium,
  siSubstack,
  siNotion,
  siFigma,
  siBehance,
  siDribbble,
  siDocker,
  siKubernetes,
  siVercel,
  siNetlify,
  siCloudflare,
  siNpm,
  siYarn,
  siPython,
  siJavascript,
  siTypescript,
  siReact,
  siNextdotjs,
  siWordpress,
  siShopify,
  siStripe,
];

const toCatalogEntry = (icon) => ({
  name: icon.slug,
  label: icon.title,
  svg: icon.svg,
  source: icon.source,
  hex: icon.hex,
  provider: 'simple-icons',
});

const legacyNames = new Set(LEGACY_FONT_AWESOME_ICONS.map((icon) => icon.name));
export const SIMPLE_ICONS = SIMPLE_ICON_SET.map(toCatalogEntry)
  .filter((icon) => !legacyNames.has(icon.name));

// Backward-compatible export name used by existing components.
export const FONT_AWESOME_ICONS = [...LEGACY_FONT_AWESOME_ICONS, ...SIMPLE_ICONS];

export const getIconHtml = (icon) => {
  if (typeof icon === 'object' && icon !== null) {
    if (icon.svg) return icon.svg;
    const prefix = icon.prefix || 'fas';
    return `<i class="${prefix} fa-${icon.name}"></i>`;
  }
  return `<i class="fas fa-${icon}"></i>`;
};
