/**
 * Resilient postinstall: runs "prisma generate" only if the prisma CLI is
 * available (dev install). In production installs (npm prune --omit=dev)
 * where prisma is absent, exits silently.
 *
 * Errors from prisma generate are printed as warnings but never abort the
 * install - common on Windows when the query engine DLL is locked, or when
 * the client was already generated by "npm run build" before deployment.
 */

const { spawnSync } = require("child_process");
const path = require("path");
const fs = require("fs");

const prismaPkg = path.join(__dirname, "..", "node_modules", "prisma", "package.json");

if (!fs.existsSync(prismaPkg)) {
  console.log("postinstall: prisma CLI not found (production install) - skipping prisma generate");
  process.exit(0);
}

console.log("postinstall: running prisma generate");
const result = spawnSync("npx", ["prisma", "generate"], {
  stdio: "inherit",
  shell: true,
});

if (result.status !== 0) {
  console.warn("postinstall: prisma generate exited with code", result.status,
    "- this is usually harmless if the client is already generated (e.g. Windows DLL lock).");
}

// Always exit 0 to not break npm install
process.exit(0);
